import {access, mkdir, writeFile} from 'node:fs/promises';
import {readFileSync} from 'node:fs';
import path from 'node:path';

import {importSb3} from '../src/sb3/import/importProject.ts';
import type {ImportMode} from '../src/sb3/import/diagnostics.ts';
import type {DslProject} from '../src/validation/projectValidator.ts';
import {resolveWorkspaceProjectDirectory, WorkspaceProjectError} from './workspaceProject.ts';

/**
 * CLI: import an existing `.sb3` into a DslProject.
 *
 *   node --experimental-strip-types tools/importSb3.ts <file.sb3> [--strict] [--out <name>]
 *
 * Without `--out` it loads and prints a summary (load status, target/block/
 * asset counts, extensions, diagnostics). With `--out <name>` it also writes an
 * editable workspace project at `workspace/<name>/` (project.ts + assets/ +
 * assets.json + output/) so the imported project can be previewed, edited, and
 * re-exported with `npm run preview` / `npm run sb3`. This is the read side of
 * the export pipeline (tools/exportSb3.ts).
 */

const MIME_TYPES: Record<string, string> = {
    svg: 'image/svg+xml', png: 'image/png', jpg: 'image/jpeg', jpeg: 'image/jpeg',
    bmp: 'image/bmp', gif: 'image/gif', wav: 'audio/wav', wave: 'audio/wav',
    mp3: 'audio/mpeg', ogg: 'audio/ogg', m4a: 'audio/mp4'
};
const mimeFor = (dataFormat: string): string => MIME_TYPES[dataFormat.toLowerCase()] ?? 'application/octet-stream';

const directoryExists = async (directory: string): Promise<boolean> => {
    try {
        await access(directory);
        return true;
    } catch {
        return false;
    }
};

/**
 * Writes an imported DslProject as an editable workspace project. Sets each
 * asset's repo-relative `source`, writes its bytes, emits a matching
 * assets.json, and serializes project.ts. Refuses to overwrite an existing
 * workspace entry.
 */
const writeWorkspaceProject = async (
    name: string,
    project: DslProject,
    assetBytes: Map<string, Uint8Array>
): Promise<{directory: string; written: number; missing: string[]}> => {
    const directory = resolveWorkspaceProjectDirectory(name);
    if (await directoryExists(directory)) {
        throw new Error(`Workspace entry already exists: ${directory}\nChoose a different --out name or remove the directory first.`);
    }
    await mkdir(path.join(directory, 'assets'), {recursive: true});
    await mkdir(path.join(directory, 'output'), {recursive: true});

    const missing: string[] = [];
    let written = 0;
    const manifest = {assets: [] as Array<Record<string, string>>};
    for (const asset of project.assets) {
        const source = `workspace/${name}/assets/${asset.md5ext}`;
        asset.source = source;
        const bytes = assetBytes.get(asset.md5ext);
        if (!bytes) {
            missing.push(asset.md5ext);
        } else {
            await writeFile(path.join(directory, 'assets', asset.md5ext), bytes);
            written++;
        }
        manifest.assets.push({
            assetId: asset.id, md5ext: asset.md5ext, dataFormat: asset.dataFormat,
            kind: asset.kind, mimeType: mimeFor(asset.dataFormat), source
        });
    }

    project.meta = {...project.meta, source: `workspace/${name}/project.ts`};

    const projectFile = `import type {DslProject} from '../../src/validation/projectValidator.ts';

// Generated by \`npm run import -- <file.sb3> --out ${name}\`. Edit and re-export
// with \`npm run sb3 -- ${name}\` or preview with \`npm run preview -- ${name}\`.
const project = ${JSON.stringify(project, null, 2)} as DslProject;

export default project;
`;
    await writeFile(path.join(directory, 'project.ts'), projectFile);
    await writeFile(path.join(directory, 'assets.json'), `${JSON.stringify(manifest, null, 2)}\n`);

    return {directory, written, missing};
};

const args = process.argv.slice(2);
const filePath = args.find(arg => !arg.startsWith('--'));
const mode: ImportMode = args.includes('--strict') ? 'strict' : 'compatibility';
const outIndex = args.indexOf('--out');
const outName = outIndex !== -1 ? args[outIndex + 1] : undefined;

const run = async (): Promise<void> => {
    if (!filePath) {
        console.error('Usage: node --experimental-strip-types tools/importSb3.ts <file.sb3> [--strict] [--out <name>]');
        process.exitCode = 1;
        return;
    }

    const bytes = new Uint8Array(readFileSync(path.resolve(filePath)));
    console.log(`Importing ${path.basename(filePath)} (${(bytes.length / 1_048_576).toFixed(1)} MiB, mode=${mode})`);

    const started = Date.now();
    const result = importSb3(bytes, outName ? {mode, projectId: outName, projectName: outName} : {mode});
    const elapsed = Date.now() - started;

    const errors = result.diagnostics.filter(d => d.severity === 'error');
    const warnings = result.diagnostics.filter(d => d.severity === 'warning');
    const byCode = new Map<string, number>();
    for (const d of result.diagnostics) byCode.set(d.code, (byCode.get(d.code) ?? 0) + 1);
    const topCodes = [...byCode.entries()].sort((a, b) => b[1] - a[1]);

    console.log(`\nLoaded: ${result.valid ? 'YES (no errors)' : 'with errors'}  in ${elapsed} ms`);
    if (result.project) {
        const p = result.project;
        const blockCount = [p.stage, ...p.sprites].reduce((sum, t) => sum + Object.keys(t.blocks).length, 0);
        console.log(`  targets:    ${1 + p.sprites.length} (Stage + ${p.sprites.length} sprites)`);
        console.log(`  blocks:     ${blockCount}`);
        console.log(`  monitors:   ${p.monitors.length}`);
        console.log(`  extensions: ${p.extensions.length ? p.extensions.join(', ') : '(none)'}`);
        console.log(`  assets:     ${p.assets.length} referenced, ${result.assets.size} bytes-entries in archive`);
    }

    console.log(`\nDiagnostics: ${errors.length} error(s), ${warnings.length} warning(s)`);
    for (const [code, count] of topCodes.slice(0, 15)) console.log(`  ${String(count).padStart(6)}  ${code}`);
    if (errors.length > 0) {
        console.log('\nFirst errors:');
        for (const d of errors.slice(0, 10)) console.log(`  [${d.code}] ${d.path}: ${d.message}`);
    }

    if (outName) {
        if (!result.project) {
            console.error('\nCannot write workspace project: import did not produce a project.');
            process.exitCode = 1;
            return;
        }
        if (errors.length > 0) {
            console.log('\nNote: the imported project has validation errors; preview/export may reject it.');
        }
        const {directory, written, missing} = await writeWorkspaceProject(outName, result.project, result.assets);
        console.log(`\nWrote workspace project: ${directory}`);
        console.log(`  project.ts, assets.json, ${written} asset file(s), output/`);
        if (missing.length > 0) console.log(`  WARNING: ${missing.length} referenced asset(s) had no bytes in the archive.`);
        console.log('\nNext:');
        console.log(`  npm run preview -- ${outName}`);
        console.log(`  npm run sb3 -- ${outName}`);
    }

    process.exitCode = result.valid ? 0 : 1;
};

run().catch(error => {
    if (error instanceof WorkspaceProjectError) {
        for (const diagnostic of error.diagnostics) console.error(`[${diagnostic.severity}] ${diagnostic.code}: ${diagnostic.message}`);
    } else {
        console.error(error instanceof Error ? error.stack ?? error.message : String(error));
    }
    process.exitCode = 1;
});
